module.exports = {
  CHOOSE_USER_CLIENT: 'CHOOSE_USER_FROM_CLIENT',
  CHOOSE_USER_SERVER: 'CHOOSE_USER_FROM_SERVER',
  ADD_MESSAGE_CLIENT: 'ADD_MESSAGE_FROM_CLIENT',
  ADD_MESSAGE_SERVER: 'ADD_MESSAGE_FROM_SERVER',
  ENABLE_USER_SERVER: 'ENABLE_USER_FROM_SERVER',
  SEND_LAST_MESSAGES: 'SEND_LAST_MESSAGES_FROM_SERVER'
}

